version: "3"
services:
  syz-rrr:
    build: syz-rrr
    network_mode: host
    volumes:
      - ./syz-rrr/rrr:/root/rrr
      - ./kdo:/root/kdo
      - ../repros/:/root/repro
      - ../linux/:/root/kernel
      - ../db/:/root/db
      - ./out:/root/out
    environment:
      - PYTHONPATH=/root
